spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///C://config"
        git:
          uri: "https://github.com/OukSaksith/micro-core-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #rabbitmq:
    #host: "localhost"
    #port: 5672
    #username: "guest"
    #password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "5A21gLsI4F6VRdvnvndN5GJZx7x8d9jJ"

server:
  port: 8071